### ISSUE TITLE
Is the n parameter still required for volume_transmitter_alberto?

### ISSUE THREAD

**Issue by AliceGem** [alberto-antonietti/CerebNEST#10]
Additional parameter vt number ("n") required for multithreading simulations with plasticity. Can't this be done internally since we just give each volume transmitter an incrementing ID?

```
            for n,vti in enumerate(vt):
        		nest.SetStatus([vti],{"deliver_interval" : 2})            # TO CHECK
        		nest.SetStatus([vti],{"n" : n})
```

**Comment by Helveg** [comment]
I opened an [issue](https://github.com/nest/nest-simulator/issues/1317) to get an explanation on how to provide custom functions in a module. This should allow us to internalize these extra steps by exposing a `CreateTeacher` function.
