### ISSUE TITLE
CereNEST does not compile for Python 3.8+, missing function cgi.escape()

### ISSUE THREAD

**Issue by cristianoalessandro** [alberto-antonietti/CerebNEST#14]
Looks like cgi.escape() was removed in Python 3.8+, so CerebNEST does not compile

```
Traceback (most recent call last):
  File "generate_help.py", line 135, in <module>
    line = cgi.escape(line)
AttributeError: module 'cgi' has no attribute 'escape'
CMakeFiles/generate_help.dir/build.make:57: recipe for target 'generate_help' failed
make[2]: *** [generate_help] Error 1
CMakeFiles/Makefile2:173: recipe for target 'CMakeFiles/generate_help.dir/all' failed
make[1]: *** [CMakeFiles/generate_help.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

```

https://github.com/Supervisor/supervisor/issues/1257

**Comment by alberto-antonietti** [comment]
@cristianoalessandro is for sure @Helveg's fault if you switched to Python3.8+ instead of the good old 3.6 👅

**Comment by Helveg** [comment]
Where does this `generate_help.py` come from, it doesn't seem to be in the source code?

**Comment by alberto-antonietti** [comment]
It's the NEST help generator:

https://github.com/nest/nest-simulator/blob/master/extras/help_generator/generate_help.py

**Comment by Helveg** [comment]
Ok, so it's an upstream bug? Could you report it Albe if there's nothing to be done about it?

**Comment by alberto-antonietti** [comment]
https://github.com/nest/nest-simulator/commit/4d8d7dca33fdd0ba61d3244c8e8898765aef7505

Already fixed in the master, but we are using NEST 2.18.

@cristianoalessandro I suggest to just comment that line out when compiling on your PC

**Comment by cristianoalessandro** [comment]
Python 3.8+ also breaks the make of Nest (they are also fixing it already
according to the github). I have switched back to Python 3.6, which works
just fine.

**Comment by alberto-antonietti** [comment]
Good move! 👍 👍
